### ISSUE TITLE
"npm i" command always gives error.

### ISSUE THREAD

**Issue by harishree7** [openblockcc/openblock-desktop#2]
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'I:\\openblock\\openblock-desktop\\node_modules\\nodegit',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'I:\openblock\openblock-desktop\node_modules\nodegit'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'I:\\openblock\\openblock-desktop\\node_modules\\nodegit'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path I:\openblock\openblock-desktop\node_modules\@abandonware\noble
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@4.0.0
npm ERR! gyp info using node@14.17.0 | win32 | x64
npm ERR! gyp info spawn c:\Python27\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'I:\\openblock\\openblock-desktop\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-G',
npm ERR! gyp info spawn args   'msvs_version=2017',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'I:\\openblock\\openblock-desktop\\node_modules\\@abandonware\\noble\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'I:\\openblock\\openblock-desktop\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\haris\\.node-gyp\\14.17.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\haris\\.node-gyp\\14.17.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=I:\\openblock\\openblock-desktop\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\Users\\haris\\.node-gyp\\14.17.0\\<(target_arch)\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=I:\\openblock\\openblock-desktop\\node_modules\\@abandonware\\noble',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'I:\\openblock\\openblock-desktop\\node_modules\\@abandonware\\noble\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "I:\openblock\openblock-desktop\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
npm ERR!     sys.exit(gyp.script_main())
npm ERR!   File "I:\openblock\openblock-desktop\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
npm ERR!     return main(sys.argv[1:])
npm ERR!   File "I:\openblock\openblock-desktop\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
npm ERR!     return gyp_main(args)
npm ERR!   File "I:\openblock\openblock-desktop\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
npm ERR!     options.duplicate_basename_check)
npm ERR!   File "I:\openblock\openblock-desktop\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
npm ERR!     generator.CalculateVariables(default_variables, params)
npm ERR!   File "I:\openblock\openblock-desktop\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1916, in CalculateVariables
npm ERR!     generator_flags.get('msvs_version', 'auto'))
npm ERR!   File "I:\openblock\openblock-desktop\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
npm ERR!     versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
npm ERR! KeyError: '2017'
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (I:\openblock\openblock-desktop\node_modules\node-gyp\lib\configure.js:345:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19043
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "I:\\openblock\\openblock-desktop\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd I:\openblock\openblock-desktop\node_modules\@abandonware\noble
npm ERR! gyp ERR! node -v v14.17.0
npm ERR! gyp ERR! node-gyp -v v4.0.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\haris\AppData\Local\npm-cache\_logs\2021-06-18T06_44_50_205Z-debug.log

//Please help me. How to solve this issue.?

**Comment by jigneshk5** [comment]
How you solved this issue @harishree7
