### ISSUE TITLE
Not able to Upload the .ob file which is already saved

### ISSUE THREAD

**Issue by CeemaCR** [openblockcc/openblock-desktop#23]
Saw the same issue is reported by another user too and it is noted as a bug. I am not getting any errors when I try for the first time.  
1. Created an .ob file and tried to save it on the computer
2. It is getting saved
3. Tried to load the saved project file. It loaded successfully. But, then the 'Upload Button' is not having any action
4. Then, pulled another .ob file, which is already saved. Then, the error reported by the other user is coming for me too

Please see the video

https://user-images.githubusercontent.com/82566442/133768711-a0933054-23ca-4244-8a98-33ee56e8acb5.mp4

**Comment by Ceema1973** [comment]
Saw that this issue is reported already. But, I am not getting any eeror

**Comment by zhengyangliu** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    replied to you on gitter.Some time ago, my grandfather fell down and was hospitalized. I have been accompanying him in the hospital. Recently, I have been troubled by this bug for a long time. I have been concentrating on repairing this problem, so I didn't pay attention to my last email.
 

    On 9/17/2021 ***@***.***> wrote： 



Saw that this issue is reported already. But, I am not getting any eeror

**Comment by zhengyangliu** [comment]
Repeat with https://github.com/openblockcc/openblock-desktop/issues/21

**Comment by CeemaCR** [comment]
Hi Arthur,

    Thank you so much. Will implement this. Thanks a lot..

**Comment by CeemaCR** [comment]
.ob code loading  is working fine now , but the upload button is not working.

**Comment by zhengyangliu** [comment]
Yse, this bug has been reported by ircbloqcc. You can check this https://github.com/openblockcc/openblock-desktop/issues/21  to see how the bug is triggered and how to temporarily solve the problem. I'll fix it in the next version.
