### ISSUE TITLE
Edit option in code area

### ISSUE THREAD

**Issue by ircbloqcc** [openblockcc/openblock-desktop#28]
Is it possible to add edit option in code generating area? 
After edited, edited code only should get upload like that can we do?

**Comment by ircbloqcc** [comment]
Thanks for updating.. Just one thing I want to conform.
if i save the edited code and load again means will edited code will appear or have to edit again?

**Comment by zhengyangliu** [comment]
No, the editor will not save these temporarily modified code.

**Comment by zhengyangliu** [comment]
Once you relock the editor, all modifications within the code editor will be removed and regenerated by the blocks which in workspace.

**Comment by ircbloqcc** [comment]
Yes. Thank you
