### ISSUE TITLE
Mac Build - Upload Issue

### ISSUE THREAD

**Issue by CeemaCR** [openblockcc/openblock-desktop#31]
When we try to upload in Mac, we are getting the following error

![image](https://user-images.githubusercontent.com/82566442/139234597-51c6394a-f3cc-4114-803b-4d33593a16c3.png)
and a javascript error

![image](https://user-images.githubusercontent.com/82566442/139234962-b7aae334-c481-4f5d-a384-f9eef4efa101.png)

What could be the reason, please advise. Thank you

**Comment by zhengyangliu** [comment]
I will see what went wrong.

**Comment by CeemaCR** [comment]
Thank you, will wait for the update

**Comment by CeemaCR** [comment]
Also with Mac source code 2.8.8, when we took a build, the first time it showed all the devices in it. But, when we took build with the same code next time few devices only are showing in it. As you have mentioned in Issue 21 for windows (closed issue), we tried to clear the cache and all, but still, it's showing a few devices only.  But its windows build is showing all devices after clearing the cache.

![image](https://user-images.githubusercontent.com/82566442/140512278-92b606d1-9d75-49a6-be43-fd2344423218.png)

**Comment by CeemaCR** [comment]
Sorry, but, is there any solution for this issue...

**Comment by zhengyangliu** [comment]
I am sure that this problem is no longer in the v2.3.0 version.

**Comment by CeemaCR** [comment]
Thank you ...
