### ISSUE TITLE
Is required costumes and sound tab in upload mode?

### ISSUE THREAD

**Issue by ircbloqcc** [openblockcc/openblock-desktop#33]
Is any use of costumes tab and sound tab in code upload mode? 
Can we hide these two tabs in program mode, right?

**Comment by zhengyangliu** [comment]
I will list this requirement in the next version of the update plan.

**Comment by zhengyangliu** [comment]
Resolvedin https://github.com/openblockcc/openblock-gui/commit/918db46c83372160eb9b35f6d15d9697d52bcbd9
