### ISSUE TITLE
When the two blocks are combined together, the wrong code is generated 

### ISSUE THREAD

**Issue by GreateChivalrous** [openblockcc/openblock-desktop#38]
when “event_whenmicrobitbuttonpressed” and "control_forever" are combined together,the code generated is wrong,there is not a entry for the progarm

**Comment by zhengyangliu** [comment]
![image](https://user-images.githubusercontent.com/10896145/147865377-7c15ac9f-7b3f-42e2-897c-7d63824198eb.png)
![image](https://user-images.githubusercontent.com/10896145/147865399-9e5278cc-5076-46a6-b7fa-45dbbeb721ab.png)
Block structures starting with other heads will cause similar problems.
