### ISSUE TITLE
Bug: Variable adding with custom blocks

### ISSUE THREAD

**Issue by ircbloqcc** [openblockcc/openblock-desktop#40]
While adding change variable blocks in custom block, **global** keyword should add. but in OB is not happening. so it gives error.
### Expected Behavior

def on_button_a():
      global test
      test += 5

def on_pin0():
     global test
     test += 20`

### Actual Behavior

![Screenshot 2022-01-04 194710](https://user-images.githubusercontent.com/86342573/148074166-abd83aa9-d005-4164-9d60-5b49a19aa593.png)

i have tried with python code. that also gives error.

![Screenshot 2022-01-04 200109](https://user-images.githubusercontent.com/86342573/148074306-4176235a-1d55-407e-92c0-4e17d28a3afe.png)

**Comment by zhengyangliu** [comment]
You are right. The code should be like this:
```python
from microbit import *

test = 0

test = 0

def repeat():
  if button_a.is_pressed():
    on_button_a()

def on_button_a():
  global test
  test += 1

while True:
  repeat()

```

**Comment by zhengyangliu** [comment]
I will fix this soon.
