### ISSUE TITLE
Linux 版本的打包依然不支持？

### ISSUE THREAD

**Issue by ysun** [openblockcc/openblock-desktop#42]
### Expected Behavior

rpm install
rpm run dist
生成Linux下的可执行项目

### Actual Behavior

could not find a release for openblockcc/openblock-tools (linux x64) 

### Steps to Reproduce

rpm install
rpm run dist

### Operating System and Browser

Ubuntu 20.04 LTS

### Related issue
#1

**Comment by zhengyangliu** [comment]
Yes, there is currently no adaptation to the linux version.
