### ISSUE TITLE
npm start Error: openblock-resource

### ISSUE THREAD

**Issue by ircbloqcc** [openblockcc/openblock-desktop#43]
Npm start is showing some error. Pls help

![Screenshot 2022-01-19 112704](https://user-images.githubusercontent.com/86342573/150072769-b7423715-e700-46fe-84c5-90f7ec6aa12d.png)

**Comment by zhengyangliu** [comment]
At present, the entire project structure will undergo an adjustment and upgrade. During this process, there will be some incompatibilities or problems that cannot be successfully compiled. It is recommended to return to the latest release version for secondary development.
