### ISSUE TITLE
Reg: Multiple openblock application

### ISSUE THREAD

**Issue by ircbloqcc** [openblockcc/openblock-desktop#44]
Is it possible to open multiple Openblock application on same time?
I mean i want to program two device(Arduino Uno and ESP8266) at same time using openblock. is it possible?

**Comment by zhengyangliu** [comment]
This feature will be added in v 2.3.0.

**Comment by zhengyangliu** [comment]
It has been supported by v2.3.0 https://github.com/openblockcc/openblock-desktop/releases/tag/v2.3.0.
