### ISSUE TITLE
select different datatype in variable creation?

### ISSUE THREAD

**Issue by ircbloqcc** [openblockcc/openblock-desktop#45]
Instead of creating default float datatype in variable.
Can you make an option to select data types like integer/float/string in Variable creation?

![Screenshot 2022-02-06 101505](https://user-images.githubusercontent.com/86342573/152668132-1e0ac8e9-b580-4813-8d42-87a3ebd2092a.png) ![Screenshot 2022-02-06 101749](https://user-images.githubusercontent.com/86342573/152668147-14d4ee78-2f5b-4862-aabe-ce92150f9216.png)

**Comment by zhengyangliu** [comment]
An overly complex variable system will cause confusion for beginners, and this function requires a lot of code modification. We are currently planning to write an advanced variable extension to implement this function, similar to the current 'insert source code'.

**Comment by ircbloqcc** [comment]
Yeah, Got it :)
