### ISSUE TITLE
Sprites are not working when i build .exe 

### ISSUE THREAD

**Issue by PatelManav20** [openblockcc/openblock-desktop#47]
Sprites are working normally when i run openblock gui but when i build the openblock desktop it does not work.

In .exe the sprite are showing in choose a sprite but when i click on the sprite it does not load on the canvas.

but the same thing works in openblock-gui.

Operating System- Windows 10

**Comment by zhengyangliu** [comment]
Follow the wiki instructions, remember to fetch static resources, otherwise resource files such as sprites will be missing from the desktop, causing you to be unable to load them.
