### ISSUE TITLE
Can't able modify external-resource.

### ISSUE THREAD

**Issue by ircbloqcc** [openblockcc/openblock-desktop#61]
In previous version openblock, if i try to add some extension means it will work.
but in new version, its not opening. 
if this is the feature means how can i add third party extension? how to check that?

![Screenshot 2022-03-12 134901](https://user-images.githubusercontent.com/86342573/158010164-44bd54bf-3567-4bb3-853c-3d57bde00355.png)

**Comment by zhengyangliu** [comment]
Follow the config file format in the official extension. Just delete the sha256 to skip the checksum step. I'll update the wiki later detailing this.

**Comment by zhengyangliu** [comment]
Like this
```
{
    "updater": {
        "default": {
            "provider": "github",
            "repo": "openblockcc/external-resources-v2"
        }
    }
}

```

**Comment by ircbloqcc** [comment]
cool... working..
