### ISSUE TITLE
Sprite Upload Error: TypeError: Cannot read properties of undefined (reading 'get')

### ISSUE THREAD

**Issue by firstnamenie** [openblockcc/openblock-desktop#63]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser
![20220513172323](https://user-images.githubusercontent.com/49673786/168254209-1a15525f-2adb-40a4-9f96-9eb4e2da08f9.png)

_e.g. Mac OS 10.11.6 Safari 10.0_

when  package offline version , Select sprite ,It is report Sprite Upload Error: TypeError: Cannot read properties of undefined (reading 'get') what happen it is?

**Comment by zhengyangliu** [comment]
You need to update all package version and external resource version. The Arduino Nano has been delete in recently version.
