### ISSUE TITLE
win10 32位系统 基于64位处理器使用-win的包时报错

### ISSUE THREAD

**Issue by anywo** [openblockcc/openblock-desktop#67]
### Expected Behavior

正常安装

### Actual Behavior

![IMG_20221026_223705](https://user-images.githubusercontent.com/57926926/198060678-91322f64-e10d-4206-be4a-0d913c84dd8a.jpg)

### Steps to Reproduce

在32位win10系统，基于64位处理器的环境安装自动选择32位和64位的安装包

### Operating System and Browser

win10专业版32位，基于64位处理器
![mmexport1666794862124](https://user-images.githubusercontent.com/57926926/198061775-5c7b9fa5-39de-4913-9e19-3c96595d68f9.jpg)

**Comment by zhengyangliu** [comment]
I will check for it.

**Comment by anywo** [comment]
Please take the trouble.

**Comment by zhengyangliu** [comment]
This issue seems to have been fixed, at least I can't reproduce it at the moment.
