### ISSUE TITLE
保存文件到盘符根目录报错EPERM: operation not permitted, mkdir 'E:\'

### ISSUE THREAD

**Issue by anywo** [openblockcc/openblock-desktop#68]
### Expected Behavior
保存到D、E等盘符的根目录

### Actual Behavior
报错EPERM: operation not permitted, mkdir 'E:\'

### Steps to Reproduce
> 1. 打开应用
> 2. 点击保存
> 3. 选择盘符根目录
> 4. 点击保存
> 5. 报错发生

### Operating System and Browser
OS: windows11 家庭版
Openblock2.4.0

**Comment by anywo** [comment]
查看源码用的时move，我试了下copy方法跨盘符根目录没事，不知道修改成copy+remove会不会好点

**Comment by zhengyangliu** [comment]
This is an bug which cause by fs-extra: https://github.com/jprichardson/node-fs-extra/issues/819. I have update this pkg to 10.x.x to fix this.
