### ISSUE TITLE
make ios and linux version make exe in error

### ISSUE THREAD

**Issue by Parmarjaimin568** [openblockcc/openblock-desktop#76]
my window version makes exe complete but this repository runs in Linux and IOS In Make exe there are some errors

Linux in  IOS does not make exe completely

IOS version in error in main.js from terser
errors:error:0308010C: Digital envelope routines: unsupported 
          at new hash(node/internal/crypto/hash:79:19)
          at object. create Hash(node:crypto:139:10)

**Comment by zhengyangliu** [comment]
1. The project does not exist the iOS version, it only supports macOS.
2. If you want to package the Linux version, you should run the packaging program in the Linux system.
