### ISSUE TITLE
Bug in Desktop application Version 2.2.0

### ISSUE THREAD

**Issue by ircbloqcc** [openblockcc/openblock-desktop#8]
In Desktop Version 2.2.0.
If i tried to open saved project,i am getting error like this.
But in V2.1.1, this problem was not there..

How to Solve this Error?

![Screenshot (14)](https://user-images.githubusercontent.com/86342573/125289326-c0f8b600-e33c-11eb-9c7f-4027e513ddda.png)

**Comment by zhengyangliu** [comment]
I've received similar bug reports, but I haven't been able to reproduce this situation stably, so it's hard to fix it. But I'll try to fix it in the next 2.2. X release.

**Comment by ircbloqcc** [comment]
Thank you,
Expecting soon with AI extension

**Comment by zhengyangliu** [comment]
At present, AI extension are not included in the mainline development plan. You can launch a vote to see which function of AI extensions people prefer, or you can develop one by yourself. I will try my best to help you.

**Comment by ircbloqcc** [comment]
Yes, I will try to add. But still i am new in this programming. How much time it will take to me i dont know..
Thank you :)

**Comment by zhengyangliu** [comment]
This bug should have been fixed In https://github.com/openblockcc/openblock-gui/commit/21b9b56c186d50bab4a8b0a948dc13e1d3441279.

**Comment by ircbloqcc** [comment]
Still the issues there in Version 2.2.2.
If i opened the Saved project from location where i saved by Double click. OpenBlock App is opening But Project is not Loading. It shows EMPTY.
![Screenshot (32)](https://user-images.githubusercontent.com/86342573/127331809-98e0d5e4-5a18-41ea-a9ed-23098bc73159.png)
